; ----------------------------------
; Reminder - Illustro Style
; Author: Ghost
; Based on illustro Clock skin (Windows)
; ----------------------------------

[Rainmeter]
Update=1000
Background=#@#Background.png
BackgroundMode=3
BackgroundMargins=0,34,0,14
AccurateText=1

[Metadata]
Name=Reminder
Author=Ghost
Information=A sticky note styled like illustro Clock.
Version=1.0

; ----------------------------------
; VARIABLES
; ----------------------------------
[Variables]
fontName=Trebuchet MS
textSize=8
colorText=255,255,255,205
noteTitle=Reminder
colorHighlight=235,170,0,255
HoverOverColor= 5,234,0,255


[styleLeftText]
StringAlign=Left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1


; ----------------------------------
; STYLES (same as illustro Clock)
; ----------------------------------

[styleTitle]
StringAlign=Center
StringCase=Upper
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorText#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleLeftText]
StringAlign=Left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleSeperator]
SolidColor=255,255,255,15

; ----------------------------------
; METERS (actual visual elements)
; ----------------------------------

; HEAD TITLE
[meterTitle]
Meter=String
MeterStyle=styleTitle
Text=#noteTitle#
X=100
Y=12
W=190
H=18


; ------------------Line 1--------------------------
; INNNER TEXT
[meterstart]
Meter=String
MeterStyle=styleLeftText
Text=- Code Daily: (
X=10
Y=40
W=190
H=40

[meterLeetcode]
; Meter=Image
; ImageName=#@#icons\leetcode1.png
; X=([meterstart:X]+70)
; Y=([meterstart:Y])
; W=14
; H=14
; LeftMouseUpAction=["https://leetcode.com/problemset/"]
; ImageTint=255,255,255,255
; MouseOverAction=[!SetOption meterLeetcode ImageTint "#HoverOverColor#"][!UpdateMeter meterLeetcode][!Redraw]
; MouseLeaveAction=[!SetOption meterLeetcode ImageTint "255,255,255,255"][!UpdateMeter meterLeetcode][!Redraw]
Meter=String
MeterStyle=styleLeftText
Text=Leetcode
FontColor=#colorHighlight#
X=([meterstart:X]+72)
Y=([meterstart:Y])
W=50
LeftMouseUpAction=["https://leetcode.com/problemset/"]
MouseOverAction=[!SetOption meterLeetcode FontColor "#HoverOverColor#"][!UpdateMeter meterLeetcode][!Redraw]
MouseLeaveAction=[!SetOption meterLeetcode FontColor "#colorHighlight#"][!UpdateMeter meterLeetcode][!Redraw]

[meterssmalltext]
Meter=String
MeterStyle=styleLeftText
Text=,
X=([meterLeetcode:X]+[meterLeetcode:W]-5)
Y=([meterstart:Y])

[meterGFG]
Meter=String
MeterStyle=styleLeftText
Text=GFG
FontColor=#colorHighlight#
X=([meterssmalltext:X]+5)
Y=([meterstart:Y])
LeftMouseUpAction=["https://www.geeksforgeeks.org/problem-of-the-day"]
MouseOverAction=[!SetOption meterGFG FontColor "#HoverOverColor#"][!UpdateMeter meterGFG][!Redraw]
MouseLeaveAction=[!SetOption meterGFG FontColor "#colorHighlight#"][!UpdateMeter meterGFG][!Redraw]

[meterssmalltext1]
Meter=String
MeterStyle=styleLeftText
Text=,
X=([meterGFG:X]+[meterGFG:W]+22)
Y=([meterstart:Y])

[meterCODEFORCES]
Meter=String
MeterStyle=styleLeftText
Text=CF
FontColor=#colorHighlight#
X=([meterssmalltext1:X]+5)
Y=([meterstart:Y])
LeftMouseUpAction=["https://codeforces.com/problemset?order=BY_SOLVED_DESC"]
MouseOverAction=[!SetOption meterCODEFORCES FontColor "#HoverOverColor#"][!UpdateMeter meterCODEFORCES][!Redraw]
MouseLeaveAction=[!SetOption meterCODEFORCES FontColor "#colorHighlight#"][!UpdateMeter meterCODEFORCES][!Redraw]

[meterssmalltext2]
Meter=String
MeterStyle=styleLeftText
Text=)
X=([meterCODEFORCES:X]+13)
Y=([meterstart:Y])

; ------------------Line 2--------------------------
[MeterCourse]
Meter=String
MeterStyle=styleLeftText
Text=- Courses:
X=10
Y=55

[MeterOPENCV]
Meter=String
MeterStyle=styleLeftText
Text=OpenCV
FontColor=#colorHighlight#
X=([MeterCourse:X]+55)
Y=([MeterCourse:Y])
LeftMouseUpAction=["https://courses.opencv.org/dashboard"]
MouseOverAction=[!SetOption MeterOPENCV FontColor "#HoverOverColor#"][!UpdateMeter MeterOPENCV][!Redraw]
MouseLeaveAction=[!SetOption MeterOPENCV FontColor "#colorHighlight#"][!UpdateMeter MeterOPENCV][!Redraw]

[meterssmalltext3]
Meter=String
MeterStyle=styleLeftText
Text=,
X=([MeterOPENCV:X]+38)
Y=([MeterCourse:Y])

[MeterUDEMY]
Meter=String
MeterStyle=styleLeftText
Text=Udemy
FontColor=#colorHighlight#
X=([meterssmalltext3:X]+5)
Y=([MeterCourse:Y])
LeftMouseUpAction=["https://www.udemy.com/home/my-courses/learning/"]
MouseOverAction=[!SetOption MeterUDEMY FontColor "#HoverOverColor#"][!UpdateMeter MeterUDEMY][!Redraw]
MouseLeaveAction=[!SetOption MeterUDEMY FontColor "#colorHighlight#"][!UpdateMeter MeterUDEMY][!Redraw]

; ------------------Line 3--------------------------
[MeterGovJob]
Meter=String
MeterStyle=styleLeftText
Text=- Gov Job:
X=10
Y=70

[MeterIBPS]
Meter=String
MeterStyle=styleLeftText
Text=IBPS
FontColor=#colorHighlight#
X=([MeterGovJob:X]+55)
Y=([MeterGovJob:Y])
LeftMouseUpAction=["https://www.ibps.in/"]
MouseOverAction=[!SetOption MeterIBPS FontColor "#HoverOverColor#"][!UpdateMeter MeterIBPS][!Redraw]
MouseLeaveAction=[!SetOption MeterIBPS FontColor "#colorHighlight#"][!UpdateMeter MeterIBPS][!Redraw]
